# Generated by Django 4.0.5 on 2022-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(help_text='Title of the movie', max_length=255, primary_key=True, serialize=False)),
                ('imdb_rating', models.CharField(help_text='IMDB rating of the movie', max_length=20)),
                ('year', models.IntegerField(help_text='Year of the movie')),
                ('released', models.CharField(help_text='Released date of the movie', max_length=30)),
                ('runtime', models.CharField(help_text='Runtime of the movie', max_length=30)),
                ('genre', models.CharField(help_text='Genre of the movie', max_length=30)),
                ('rated', models.CharField(help_text='Parental guide of the movie', max_length=5, null=True)),
                ('plot', models.TextField(help_text='Plot of the movie')),
                ('director', models.CharField(help_text='Director(s) of the movie', max_length=100)),
                ('writer', models.CharField(help_text='Writer(s) of the movie', max_length=100)),
                ('actors', models.CharField(help_text='Actors and Actresses of the movie', max_length=255)),
                ('language', models.CharField(help_text='Language and Actresses of the movie', max_length=255)),
                ('poster_url', models.CharField(help_text='Poster URL of the movie', max_length=255)),
                ('country', models.CharField(help_text='Country of the movie', max_length=255)),
                ('box_office', models.CharField(help_text='BoxOffice of the movie', max_length=255)),
            ],
        ),
    ]
