# Generated by Django 4.0.5 on 2022-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the movie', max_length=255, unique=True)),
                ('imdb_rating', models.FloatField(help_text='IMDB rating of the movie')),
                ('year', models.IntegerField(help_text='Year of the movie')),
                ('parentalguide', models.CharField(help_text='Parental guide of the movie', max_length=5, null=True)),
                ('summary', models.TextField(help_text='Summary of the movie')),
                ('director', models.CharField(help_text='Director of the movie', max_length=50)),
                ('upload', models.ImageField(help_text='Conver image of the movie', upload_to='covers/')),
            ],
        ),
    ]
