# Generated by Django 4.0.5 on 2022-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='parentalguide',
            new_name='rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='upload',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default=None, help_text='Actors and Actresses of the movie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.CharField(default=None, help_text='BoxOffice of the movie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default=None, help_text='Country of the movie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(default=None, help_text='Genre of the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=None, help_text='Language and Actresses of the movie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(default=None, help_text='Plot of the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(default=None, help_text='Poster URL of the movie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.IntegerField(default=None, help_text='Released date of the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=None, help_text='Runtime of the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default=None, help_text='Writer(s) of the movie', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text='Director(s) of the movie', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Title of the movie', max_length=255, primary_key=True, serialize=False),
        ),
    ]
