# Generated by Django 4.0.5 on 2022-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_parentalguide_movie_rated_remove_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(help_text='IMDB rating of the movie', max_length=20),
        ),
    ]
